name: Firebase Test Lab

on:
  pull_request:
    branches:
      - master
      -

env:
  ROBO_TEST_RESULT: ''

jobs:
  setup-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - id: 'gcloud-auth'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v1

      - name: Authenticate Google Cloud
        run: gcloud auth activate-service-account --key-file=service-account-key.json


      - name: Set current project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}


      - name: Run Robo Test
        id: robo-test
        run: |
          gcloud firebase test android run \
          --type robo \
          --app app/app-debug.apk \
          --device model=Pixel3,version=30,locale=en,orientation=portrait \
          --timeout 1m \
          --no-record-video \
          --no-performance-metrics \
          
          sudo apt-get install xclip
          
          xclip -selection clipboard -o > robo-test-result.txt
          
          echo "{ROBO_TEST_RESULT: $(cat robo-test-result.txt)}" >> $GITHUB_OUTPUT

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run python script
        run: |
          python .github/workflows/robo-test-result.py ${{ steps.robo-test.outputs.ROBO_TEST_RESULT }} ${{ secrets.SLACK_WEBHOOK_URL }}

        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        




