name: Firebase ROBO Test

on:
  pull_request_review:
    types:
      - submitted
    branches:
      - master

env:
  DEBUG_APK_PATH: "app/build/outputs/apk/debug/app-debug.apk"
  STAGING_APK_PATH: "app/build/outputs/apk/staging/app-staging.apk"
  JAVA_VERSION: "17"
  TIMEOUT: "1m"

jobs:
  check-reviews:
    runs-on: ubuntu-latest

    outputs:
      review_approved: ${{ steps.check_reviews.outputs.review_approved }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - id: 'check_reviews'
        name: Check PR Reviews
        run: |
          python script/check_reviews.py \
          ${{ secrets.GH_TOKEN }} \
          ${{ github.repository_owner }} \
          ${{ github.event.repository.name }} \
          ${{ github.event.pull_request.number }}

  run-robo-test:
    needs: check-reviews
    if: ${{ needs.check-reviews.outputs.review_approved == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - id: 'gcloud-auth'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v1

      - name: Set current project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}


      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}


      - name: Build Staging apk
        run: |
          chmod +x gradlew
          ./gradlew assembleStaging


      - name: Run Robo Test
        id: robo-test
        run: |
          gcloud firebase test android run \
          --type robo \
          --app ${{ env.STAGING_APK_PATH }} \
          --device model=Pixel2.arm,version=33,locale=en,orientation=portrait \
          --device model=MediumPhone.arm,version=29,locale=en,orientation=portrait \
          --device model=SmallPhone.arm,version=26,locale=en,orientation=portrait \
          --device model=AndroidTablet270dpi,version=30,locale=en,orientation=portrait \
          --format=json \
          --timeout ${{ env.TIMEOUT }} \
          --no-record-video \
          --no-performance-metrics > ${{ runner.workspace }}/robo-test-result.json \


      - name: Get Apk Info
        id: apk-info
        uses: hkusu/apk-info-action@v1
        with:
          apk-path: ${{ env.STAGING_APK_PATH }}

      - name: Run Post Slack Message Script
        run: |
          python script/post_result_slack.py \
          ${{ runner.workspace }}/robo-test-result.json \
          ${{ secrets.SLACK_WEBHOOK_URL }} \
          ${{ steps.apk-info.outputs.application-name }} \
          ${{ steps.apk-info.outputs.version-name }} \
          
