name: Firebase Test Lab

on:
  pull_request:
    branches:
      - master
      -

env:
  ROBO_TEST_RESULT: ''

jobs:
  setup-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - id: 'gcloud-auth'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v1

      - name: Authenticate Google Cloud
        run: gcloud auth activate-service-account --key-file=service-account-key.json


      - name: Set current project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}


      - name: Run Robo Test
        id: robo-test
        run: |
          gcloud firebase test android run \
          --type robo \
          --app app/app-debug.apk \
          --device model=Pixel3,version=30,locale=en,orientation=portrait \
          --timeout 1m \
          --no-record-video \
          --no-performance-metrics > robo-test-result.txt
          
          echo "{ROBO_TEST_RESULT: $(cat robo-test-result.txt)}" >> $GITHUB_OUTPUT

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_MESSAGE: ${{ steps.robo-test.outputs.ROBO_TEST_RESULT }}
          SLACK_TITLE: CI Test Suite
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

        




