name: Firebase Test Lab

on:
  pull_request:
    branches:
      - master

jobs:
  setup-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - id: 'gcloud-auth'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v1

      - name: Authenticate Google Cloud
        run: gcloud auth activate-service-account --key-file=service-account-key.json


      - name: Set current project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}


      - name: Run Robo Test
        id: robo-test
        run: |
          gcloud firebase test android run \
          --type robo \
          --app app/app-debug.apk \
          --device model=Pixel3,version=30,locale=en,orientation=portrait \
          --timeout 1m \
          --format=json \
          --no-record-video \
          --no-performance-metrics > robo-test-result.json \

          result="$(cat robo-test-result.json)"
          escaped_result=$(echo $result | sed 's/"/\\"/g')

          curl -X POST -H "Content-Type: application/json" --data "{\"text\":\"$escaped_result\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
          

        




