name: Renovate PR
on: pull_request

env:
  JAVA_VERSION: 17

jobs:
  lint:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'renovate-bot')
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Lint Check
        run: |
         chmod +x gradlew
          ./gradlew lint
          echo "Lint successful"
      

  build-project:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'renovate-bot')

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Build Staging
        run: |
          chmod +x gradlew
          ./gradlew assembleStaging
          echo "Staging build successful"
          

  run-unit-tests:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'renovate-bot')

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Run Unit Tests
        run: |
          chmod +x gradlew
          ./gradlew test
          echo "Unit tests successful"
  
