name: Test CI

on:
  pull_request:
    branches:
      - master


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Send Google service file to slack
        run: |
          WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL }} \
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Google service file"}' $WEBHOOK_URL"

